// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAOHtLUCS_HuHYLfIK1CoBiL03dnByZggg',
    appId: '1:267933600841:web:ebdd7a255fa4d2b1fd0398',
    messagingSenderId: '267933600841',
    projectId: 'flutter-firebase-b2d47',
    authDomain: 'flutter-firebase-b2d47.firebaseapp.com',
    storageBucket: 'flutter-firebase-b2d47.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCStCpPdB-0t--GFREDVx2uWuQETe03In4',
    appId: '1:267933600841:android:f0fbb25bf1c28c4afd0398',
    messagingSenderId: '267933600841',
    projectId: 'flutter-firebase-b2d47',
    storageBucket: 'flutter-firebase-b2d47.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgGFMB1KZk9pKWsJHAosLd9nlflMWYU2I',
    appId: '1:267933600841:ios:06010ff23c5ba872fd0398',
    messagingSenderId: '267933600841',
    projectId: 'flutter-firebase-b2d47',
    storageBucket: 'flutter-firebase-b2d47.appspot.com',
    iosBundleId: 'com.example.firebaseTut',
  );
}
